[build]
builder = "NIXPACKS"
buildCommand = "npm i -g pnpm typescript ts-node && pnpm install"

[deploy]
startCommand = "node -r ts-node/register/transpile-only -r dotenv/config apps/hr-api/src/main.ts"
